// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserWallet = "user_wallet"

// UserWallet 用户钱包的绑定
type UserWallet struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       int64     `gorm:"column:uid;not null" json:"uid"`
	Address   string    `gorm:"column:address;not null;comment:eth:42|solana:44|ton:33|btc:" json:"address"` // eth:42|solana:44|ton:33|btc:
	ChainID   int32     `gorm:"column:chain_id;not null;comment:非evm链，可以私下用负数指定" json:"chain_id"`            // 非evm链，可以私下用负数指定
	ChainName string    `gorm:"column:chain_name;not null;comment:需要区分出测试网，例如eth-sepolia" json:"chain_name"` // 需要区分出测试网，例如eth-sepolia
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	IsDeleted int32     `gorm:"column:is_deleted;not null;comment:0:no|1:yes" json:"is_deleted"` // 0:no|1:yes
}

// TableName UserWallet's table name
func (*UserWallet) TableName() string {
	return TableNameUserWallet
}
