// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	UserLaunchTx    *userLaunchTx
	UserSwapTx      *userSwapTx
	UserTransaction *userTransaction
	UserWallet      *userWallet
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	UserLaunchTx = &Q.UserLaunchTx
	UserSwapTx = &Q.UserSwapTx
	UserTransaction = &Q.UserTransaction
	UserWallet = &Q.UserWallet
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		UserLaunchTx:    newUserLaunchTx(db, opts...),
		UserSwapTx:      newUserSwapTx(db, opts...),
		UserTransaction: newUserTransaction(db, opts...),
		UserWallet:      newUserWallet(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	UserLaunchTx    userLaunchTx
	UserSwapTx      userSwapTx
	UserTransaction userTransaction
	UserWallet      userWallet
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		UserLaunchTx:    q.UserLaunchTx.clone(db),
		UserSwapTx:      q.UserSwapTx.clone(db),
		UserTransaction: q.UserTransaction.clone(db),
		UserWallet:      q.UserWallet.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		UserLaunchTx:    q.UserLaunchTx.replaceDB(db),
		UserSwapTx:      q.UserSwapTx.replaceDB(db),
		UserTransaction: q.UserTransaction.replaceDB(db),
		UserWallet:      q.UserWallet.replaceDB(db),
	}
}

type queryCtx struct {
	UserLaunchTx    IUserLaunchTxDo
	UserSwapTx      IUserSwapTxDo
	UserTransaction IUserTransactionDo
	UserWallet      IUserWalletDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		UserLaunchTx:    q.UserLaunchTx.WithContext(ctx),
		UserSwapTx:      q.UserSwapTx.WithContext(ctx),
		UserTransaction: q.UserTransaction.WithContext(ctx),
		UserWallet:      q.UserWallet.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
