mysql:
  user: ${MYSQL_USER}
  pass: ${MYSQL_PASS}
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  db:   ${DB_NAME}

chain_config:
  - chain_id: 1
    chain_name: "ethereum-mainnet"
    url: "https://eth.drpc.org"
    uniswap_v2_router_address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    uniswap_v2_factory_address : "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
    standard_token_factory01_step: 0 # 每次爬取的块的区间，等于 0 将使用默认值，如：100
    standard_token_factory01_address: "0x82f777B726537d0b854fD0447996177c05eeC82E"
    standard_token_factory01_fee_symbol: "ETH"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 20863023 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close:  ${IS_CLOSE_ETHEREUM_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_ETHEREUM_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测
    dexpert_universal_router_step: 0 # 每次爬取的块的区间，等于 0 将使用默认值，如：100
    dexpert_universal_router_address: "0xdF2bf594cCaF8199348E9b0a6d3767dd6adB998b"
    dexpert_universal_router_block_number: 20711609 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    dexpert_universal_router_weth_address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "Ether"
    dexpert_universal_router_eth_symbol: "ETH"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_ETHEREUM_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_ETHEREUM_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
  - chain_id: 11155111
    chain_name: "ethereum-sepolia"
    url: "https://rpc.sepolia.org/"
    uniswap_v2_router_address: "0xb22cE52905d25987321d6BF73d1705886f1Cc4F4"
    uniswap_v2_factory_address : "0xce71f5957f481A77161F368AD6dFc61d694Cf171"
    standard_token_factory01_step: 0
    standard_token_factory01_address: "0x05D1c16b41620D6C0DEab24a1782eEd5A1BcA7FE"
    standard_token_factory01_fee_symbol: "ETH"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 6781627 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close:  ${IS_CLOSE_ETHEREUM_SEPOLIA_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_ETHEREUM_SEPOLIA_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
    dexpert_universal_router_step: 0
    dexpert_universal_router_address: "0xF2f344e5fBf4FA8aAC548a8401c8E023b2783A92"
    dexpert_universal_router_block_number: 6441775 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: "0xb72bc8971d5e595776592e8290be6f31937097c6"
    dexpert_universal_router_weth_address: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "Ether"
    dexpert_universal_router_eth_symbol: "ETH"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_ETHEREUM_SEPOLIA_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_ETHEREUM_SEPOLIA_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
  - chain_id: 1030
    chain_name: "Conflux-eSpace"
    url: "https://evmmain-china.confluxrpc.com"
    #    url: "https://evm.confluxrpc.com"
    uniswap_v2_router_address: "0x62b0873055bf896dd869e172119871ac24aea305"
    uniswap_v2_factory_address : "0xe2a6f7c0ce4d5d300f97aa7e125455f5cd3342f5"
    standard_token_factory01_step: 0
    standard_token_factory01_address: "0xCd8cb6776C715Ae2d7101CAF182b6A10224d71a3"
    standard_token_factory01_fee_symbol: "CFX"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 105818415 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close: ${IS_CLOSE_CONFLUX_ESPACE_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_CONFLUX_ESPACE_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
    dexpert_universal_router_step: 0
    dexpert_universal_router_address: "0x962408EDa28732fAcE8d2BD4056628de044eeEc1"
    dexpert_universal_router_block_number: 103999855 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: "0xfe97E85d13ABD9c1c33384E796F10B73905637cE"
    dexpert_universal_router_weth_address: "0x14b2D3bC65e74DAE1030EAFd8ac30c533c976A9b"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "CFX"
    dexpert_universal_router_eth_symbol: "CFX"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 18
    dexpert_universal_router_is_close: ${IS_CLOSE_CONFLUX_ESPACE_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_CONFLUX_ESPACE_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
  - chain_id: 200901
    chain_name: "bitlayer-mainnet"
#    url: "https://rpc.bitlayer.org"
    url: "https://rpc-bitlayer.rockx.com"
    uniswap_v2_router_address: "0xB0Cc30795f9E0125575742cFA8e73D20D9966f81"
    uniswap_v2_factory_address : "0x1037E9078df7ab09B9AF78B15D5E7aaD7C1AfDd0"
    standard_token_factory01_step: 0
    standard_token_factory01_address: "0x69C3926284699989B5dF13432B80171F8b3aCBe9"
    standard_token_factory01_fee_symbol: "BTC"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 4680991 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close: ${IS_CLOSE_BITLAYER_MAINNET_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_BITLAYER_MAINNET_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
    dexpert_universal_router_step: 0
    dexpert_universal_router_address: "0x4e86cBD95DeD0b00ca0D74713eb6596e4A2B4fD2"
    dexpert_universal_router_block_number: 4566111 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: "0xfe9f969faf8ad72a83b761138bf25de87eff9dd2"
    dexpert_universal_router_weth_address: "0xfF204e2681A6fA0e2C3FaDe68a1B28fb90E4Fc5F"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "BTC"
    dexpert_universal_router_eth_symbol: "BTC"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_BITLAYER_MAINNET_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_BITLAYER_MAINNET_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
  - chain_id: 169
    chain_name: "manta-mainnet"
    url: "https://manta-pacific.drpc.org"
    uniswap_v2_router_address: "0xA3C957B20779Abf06661E25eE361Be1430ef1038"
    uniswap_v2_factory_address : "0x31a78894a2B5dE2C4244cD41595CD0050a906Db3"
    standard_token_factory01_step: 0
    standard_token_factory01_address: "0x66717210bB5bA75Df52E50d77E7E2CF005C42143"
    standard_token_factory01_fee_symbol: "ETH"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 3339243 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close: ${IS_CLOSE_MANTA_MAINNET_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_MANTA_MAINNET_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
    dexpert_universal_router_step: 0
    dexpert_universal_router_address: "0xAB255ECA00D1816f35FED0cdebeA5A4C26C7C311"
    dexpert_universal_router_block_number: 3198603 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: "0xf417F5A458eC102B90352F697D6e2Ac3A3d2851f"
    dexpert_universal_router_weth_address: "0x0Dc808adcE2099A9F62AA87D9670745AbA741746"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "ETH"
    dexpert_universal_router_eth_symbol: "ETH"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_MANTA_MAINNET_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_MANTA_MAINNET_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
  - chain_id: 47763
    chain_name: "neo-x-mainnet"
    url: "https://mainnet-1.rpc.banelabs.org"
    uniswap_v2_router_address: "0x82b56Dd9c7FD5A977255BA51B96c3D97fa1Af9A9"
    uniswap_v2_factory_address : "0x753df473702cB31BB81a93966e658e1AA4f10DD8"
    standard_token_factory01_step: 0
    standard_token_factory01_address: "0x1233BD26E785bE84D006b904fc1527A227733e75"
    standard_token_factory01_fee_symbol: "GAS"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 433264 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close: ${IS_CLOSE_NEO_X_MAINNET_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_NEO_X_MAINNET_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
    dexpert_universal_router_step: 0
    dexpert_universal_router_address: "0x2cA866d3FA566fE66e86087Da3a3b8e534F9A588"
    dexpert_universal_router_block_number: 331871 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: "0x68b55E582961968ef7758D8454D8A3e78c692e0B"
    dexpert_universal_router_weth_address: "0xdE41591ED1f8ED1484aC2CD8ca0876428de60EfF"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "GAS"
    dexpert_universal_router_eth_symbol: "GAS"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_NEO_X_MAINNET_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_NEO_X_MAINNET_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
  - chain_id: 995
    chain_name: "5ire-mainnet"
    url: "https://rpc.5ire.network"
    uniswap_v2_router_address: "0xA5F3d2cAd89BA44CEb13D7e4E917f6eb180FbCaE"
    uniswap_v2_factory_address : "0xD5F2C72CB142A665b5D4987a5a5eEa5bfC53BD8c"
    standard_token_factory01_step: 0
    standard_token_factory01_address: "0x69FdF199340107102158e6D8a44aeC83Fe041A3F"
    standard_token_factory01_fee_symbol: "5ire"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 2689523 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close: ${IS_CLOSE_5IRE_MAINNET_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_5IRE_MAINNET_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
    dexpert_universal_router_step: 0
    dexpert_universal_router_address: "0x9080Cd17174FB1E2a00dF668E5C4Ff21256410bA"
    dexpert_universal_router_block_number: 2689470 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: ""
    dexpert_universal_router_weth_address: "0xCFaEB74409E4C6756C43F75455fc42A6A3FdEb1f"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "5ire"
    dexpert_universal_router_eth_symbol: "5ire"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 0
    dexpert_universal_router_is_close: ${IS_CLOSE_5IRE_MAINNET_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭, usdt address 和 decimal 需要配齐
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_5IRE_MAINNET_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
  - chain_id: 8453
    chain_name: "base-mainnet"
    url: "https://base.drpc.org/"
    uniswap_v2_router_address: "0x4752ba5dbc23f44d87826276bf6fd6b1c372ad24"
    uniswap_v2_factory_address : "0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6"
    standard_token_factory01_step: 0
    standard_token_factory01_address: "0x6643CABa0966FfF2Bed8A2f59c34E55A2e00B2ae"
    standard_token_factory01_fee_symbol: "ETH"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 20413471 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    standard_token_factory01_is_close: ${IS_CLOSE_BASE_MAINNET_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    standard_token_factory01_is_start_saved_newest_block_number: ${IS_START_BASE_MAINNET_STANDARD_TOKEN_FACTORY01_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    standard_token_factory01_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试
    dexpert_universal_router_step: 0
    dexpert_universal_router_address: "0x8E5C368667308Da4D2B3763f7bB70afB8ccbF1FF"
    dexpert_universal_router_block_number: 19968329 # 开始爬的区号，如果从已爬到的数据的最新区块开始爬，此配置项将会忽略
    dexpert_universal_router_usdt_address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    dexpert_universal_router_weth_address: "0x4200000000000000000000000000000000000006"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_eth_name: "Base"
    dexpert_universal_router_eth_symbol: "ETH"
    dexpert_universal_router_eth_decimal: 18
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_BASE_MAINNET_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭，true 关闭,
    dexpert_universal_router_is_start_saved_newest_block_number: ${IS_START_BASE_MAINNET_DEXPERT_UNIVERSAL_ROUTER_SAVED_NEWEST_BLOCK_NUMBER} # 是否从已爬到的数据的最新区块开始爬, true 表示使用
    dexpert_universal_router_is_use_newest_block_number: true # true 表示从链上最新的区块开始爬，主要用于测试

is_close_standard_token_factory01_listener: ${IS_CLOSE_STANDARD_TOKEN_FACTORY01_LISTENER} # 是否关闭 Standard Token Factory01 Listener， true 关闭
is_close_dexpert_universal_router_listener: ${IS_CLOSE_DEXPERT_UNIVERSAL_ROUTER_LISTENER} # 是否关闭 Universal Router Listener， true 关闭
