mysql:
  user: ${MYSQL_USER}
  pass: ${MYSQL_PASS}
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  db:   ${DB_NAME}

chain_config:
  - chain_id: 1
    chain_name: "ethereum-mainnet"
    url: "https://eth-mainnet.g.alchemy.com/v2/yySetlFhRixBXll8vY8B-fVbhlcsLg4a"
    uniswap_v2_router_address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    standard_token_factory01_address: "0x9Ba604031d1a00EA253D777035C588C291881204"
    standard_token_factory01_fee_symbol: "ETH"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 20711519
    standard_token_factory01_is_close:  ${IS_CLOSE_ETHEREUM_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    dexpert_universal_router_address: "0xdF2bf594cCaF8199348E9b0a6d3767dd6adB998b"
    dexpert_universal_router_block_number: 20711609
    dexpert_universal_router_usdt_address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
    dexpert_universal_router_weth_address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_ETHEREUM_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
  - chain_id: 11155111
    chain_name: "ethereum-sepolia"
    url: "https://eth-sepolia.g.alchemy.com/v2/gOeoBV9mlFL1pWj7qbKEdlB6pXTfNum6"
    uniswap_v2_router_address: "0xb22cE52905d25987321d6BF73d1705886f1Cc4F4"
    standard_token_factory01_address: "0x822935C2240E6A0b5C96E3eA355446a83ed12C03"
    standard_token_factory01_fee_symbol: "ETH"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 6641775
    standard_token_factory01_is_close:  ${IS_CLOSE_ETHEREUM_SEPOLIA_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    dexpert_universal_router_address: "0xF2f344e5fBf4FA8aAC548a8401c8E023b2783A92"
    dexpert_universal_router_block_number: 6441775
    dexpert_universal_router_usdt_address: "0xB72bC8971D5e595776592E8290bE6F31937097c6"
    dexpert_universal_router_weth_address: "0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_ETHEREUM_SEPOLIA_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
  - chain_id: 1030
    chain_name: "Conflux-eSpace"
    url: "https://evm.confluxrpc.com"
    uniswap_v2_router_address: "0x62b0873055Bf896DD869e172119871ac24aEA305"
    standard_token_factory01_address: "0x9998Bc4B6e148FC4633b274E2CC040B19638F554"
    standard_token_factory01_fee_symbol: "CFX"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 104087180
    standard_token_factory01_is_close: ${IS_CLOSE_CONFLUX_ESPACE_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    dexpert_universal_router_address: "0x962408EDa28732fAcE8d2BD4056628de044eeEc1"
    dexpert_universal_router_block_number: 103999855
    dexpert_universal_router_usdt_address: "0xfe97E85d13ABD9c1c33384E796F10B73905637cE"
    dexpert_universal_router_weth_address: "0x14b2D3bC65e74DAE1030EAFd8ac30c533c976A9b"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_usdt_decimal: 18
    dexpert_universal_router_is_close: ${IS_CLOSE_CONFLUX_ESPACE_DEXPERT_UNIVERSAL_ROUTER} # 是否关闭， true 关闭
  - chain_id: 200901
    chain_name: "bitlayer-mainnet"
    url: "https://rpc.bitlayer.org"
    uniswap_v2_router_address: "0xB0Cc30795f9E0125575742cFA8e73D20D9966f81"
    standard_token_factory01_address: "0x6f6f088bA7409E14f60aFA92D3Bee56a7BAd446B"
    standard_token_factory01_fee_symbol: "BTC"
    standard_token_factory01_fee_decimal: 18
    standard_token_factory01_block_number: 4453885
    standard_token_factory01_is_close: ${IS_CLOSE_BITLAYER_MAINNET_STANDARD_TOKEN_FACTORY01} # 是否关闭， true 关闭
    dexpert_universal_router_address: "0x4e86cBD95DeD0b00ca0D74713eb6596e4A2B4fD2"
    dexpert_universal_router_block_number: 4566111
    dexpert_universal_router_usdt_address: "0xfe9f969faf8ad72a83b761138bf25de87eff9dd2"
    dexpert_universal_router_weth_address: "0xfF204e2681A6fA0e2C3FaDe68a1B28fb90E4Fc5F"
    dexpert_universal_router_eth_address: "0x0000000000000000000000000000000000000000"
    dexpert_universal_router_usdt_decimal: 6
    dexpert_universal_router_is_close: ${IS_CLOSE_BITLAYER_MAINNET_UNIVERSAL_ROUTER} # 是否关闭， true 关闭

is_close_standard_token_factory01_listener: ${IS_CLOSE_STANDARD_TOKEN_FACTORY01_LISTENER} # 是否关闭 Standard Token Factory01 Listener， true 关闭
is_close_dexpert_universal_router_listener: ${IS_CLOSE_DEXPERT_UNIVERSAL_ROUTER_LISTENER} # 是否关闭 Universal Router Listener， true 关闭
